# Generated by Django 5.0.3 on 2024-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
