# Generated by Django 5.0.3 on 2024-03-31 18:59

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="upload",
            field=models.FileField(
                null=True, upload_to=base.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.svg",
                null=True,
                upload_to=base.models.user_directory_path,
            ),
        ),
    ]
